Fix/faq search
teamdigitale/prossimapa.gov.it-site pull request #35
Opened 2021-10-30 08:30 UTC by lollomag

2021-10-30 10:57 UTC, emnlpstr approved these changes

2021-11-02 08:55 UTC, sebbalex requested changes

2021-11-02 08:55 UTC, sebbalex commented on contents/faq-page/faq.yml
> +        content: testo due
??

2021-11-02 08:55 UTC, sebbalex commented on contents/faq-page/faq.yml
>  noResults: Nessun risultato trovato
same as above, why this?

2021-11-02 08:55 UTC, sebbalex commented on src/layouts/FaqPage.jsx
> +      console.log(inputValue);
```suggestion

```

2021-11-02 08:55 UTC, sebbalex commented on src/layouts/FaqPage.jsx
> +      // }
```suggestion

```

2021-11-02 09:26 UTC, merged