Fix/support and opportunity page
teamdigitale/prossimapa.gov.it-site pull request #51
Opened 2021-11-04 10:32 UTC by lollomag

2021-11-04 13:05 UTC, emnlpstr approved these changes

2021-11-04 14:16 UTC, sebbalex requested changes
please remove `package-lock.json` since yarn is the official tool in use here.

2021-11-04 14:16 UTC, sebbalex commented on src/layouts/Header.jsx
> +          {/* <HeaderToggler
remove comment

2021-11-05 13:43 UTC, sebbalex commented
superseded by #56

2021-11-05 13:43 UTC, closed without merging